In [1]:
#import numpy
#numpy.version.version

'1.26.4'

In [ ]:
#!pip install --upgrade numpy

In [3]:
!python ../setup.py build 

File path of setup.py: c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot
c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot\opttrot
['c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_c.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn_methods.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn_utils.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn_ext.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn_python.c']
['c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_c.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_

file c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot\opttrot\opttrot.py (for module opttrot) not found
file c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot\opttrot\opttrot.py (for module opttrot) not found


In [4]:
!python ../setup.py build_ext --inplace

File path of setup.py: c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot
c:\Users\cmat411a\Documents\GitHub\Org_OptTrot\OptTrot\opttrot
['c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_c.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn_methods.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_bn\\pauli_bn_utils.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn_ext.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\bn\\bn_python.c']
['c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_src\\pauli_c.c', 'c:\\Users\\cmat411a\\Documents\\GitHub\\Org_OptTrot\\OptTrot\\opttrot\\c_

In [3]:
import os, sys
sys.path.append("..")

In [4]:
import numpy as np
import importlib

In [5]:
from opttrot.pauli_c import _bignum_bytes, get_paulilist_from_coefs
from scipy.sparse import coo_matrix

In [6]:
mat = np.random.rand(8,8) +1j*np.random.rand(8,8)
qubit = 3
cmat = coo_matrix(mat)
cmat.row, cmat.col, cmat.data

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7],
       dtype=int32),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
        6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3,
        4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7],
       dtype=int32),
 array([0.99662805+0.27801773j, 0.3167394 +0.62261991j,
        0.63070479+0.53294914j, 0.03486708+0.23332885j,
        0.85362684+0.28281263j, 0.65374878+0.84486139j,
        0.3409182 +0.20031444j, 0.38634268+0.39305562j,
        0.22160685+0.02689089j, 0.42426078+0.30906677j,
        0.36124377+0.63946279j, 0.52339146+0.08910968j,
        0.299317  +0.90939625j, 0.71230968+0.21927465j,
        0.91876641+0.16042717j, 0.29054007+0.32532099j,
        0.05569248+0.4752711j , 0.59687403+0.82718249j,
        0.91241234+0

In [7]:

arr = get_paulilist_from_coefs(3, cmat.row.astype(np.uint64), cmat.col.astype(np.uint64), cmat.data)

In [8]:
arr[0]

PauliElement(n=3, weight=0.996628+(0.278018)j, III)

In [24]:
arr[0]

PauliElement(n=3, weight=0.466508+(0.638619)j, III)

In [21]:
arr[1]

PauliElement(n=8, weight=0.247237+(0.583988)j, IIIIIIII)

In [7]:
np.array([2**63]) + np.array([2**64])

array([27670116110564327424], dtype=object)

In [8]:
from scipy.sparse import coo_matrix

In [10]:
spa = coo_matrix(test_mat(mat))

Arr assignement was success.
Shape: (4, 5)


In [13]:
spa.row
spa.col
spa.data

array([1., 2., 1., 2., 3., 2., 3., 4.])