In [1]:
import numpy as np

In [16]:
I = np.eye(2, dtype=complex)
X = np.matrix([[0, 1], [1, 0]], dtype=complex)
Y_ = np.matrix([[0, 1], [-1, 0]], dtype=complex)
Y = np.matrix([[0, -1j], [1j, 0]], dtype=complex)
Z = np.matrix([[1, 0], [0, -1]], dtype=complex)

In [13]:
Y_@Z # -X
Z@Y_ #X
Z@X # Y
X@Z # -Y
Y_@X # Z
X@Y_ # -Z

matrix([[-1.+0.j,  0.+0.j],
        [ 0.+0.j,  1.+0.j]])

In [17]:
X@Y

matrix([[0.+1.j, 0.+0.j],
        [0.+0.j, 0.-1.j]])

In [18]:
Y@Z

matrix([[0.+0.j, 0.+1.j],
        [0.+1.j, 0.+0.j]])

matrix([[ 0.+0.j, -1.+0.j],
        [-1.+0.j,  0.+0.j]])

matrix([[ 0.+0.j,  1.+0.j],
        [-1.+0.j,  0.+0.j]])

matrix([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]])

## Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array(
    [
    [0., 1., 0.2, 3.2, 0.1, 0.00001],
    [0., 1., 0.2, 3.2, 0.1, 0.00001],
    [0., 1., 0.2, 3.2, 0.1, 0.00001],
    [0., 1., 0.2, 3.2, 0.1, 0.00001]
    ]
)

In [7]:
np.nonzero(arr>0.1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3], dtype=int64))