In [1]:
import os, sys
sys.path.append("..")
sys.path.append("..\\..")
sys.path.append(".")

In [2]:
import opttrot

In [11]:
from opttrot.pauli import PauliElement, PauliPoly

In [4]:
import numpy as np

In [60]:
gamma_1 = PauliElement(3, 2, 2, 1j)
gamma_2 = PauliElement(3, 3, 2, 1j)
gamma_3 = PauliElement(2, 3, 2, 1j)
gamma_4 = PauliElement(0, 2, 2, 1)
gammas = [
    gamma_1,
    gamma_2,
    gamma_3,
    gamma_4
]

In [61]:
gammas

[PauliElement(n=2, weight=0.000000+(1.000000)j, YX),
 PauliElement(n=2, weight=0.000000+(1.000000)j, YY),
 PauliElement(n=2, weight=0.000000+(1.000000)j, YZ),
 PauliElement(n=2, weight=1.000000+(0.000000)j, ZI)]

In [62]:
gamma1 = PauliPoly.from_iterables([gamma_1])
gamma2 = PauliPoly.from_iterables([gamma_2])
gamma3 = PauliPoly.from_iterables([gamma_3])
gamma4 = PauliPoly.from_iterables([gamma_4])

In [63]:
gamma1.matrix.real

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.],
       [-1.,  0.,  0.,  0.]])

In [67]:
gamma2.matrix.imag

array([[ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  0.]])

In [65]:
gamma3.matrix.real

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [49]:
gamma4.matrix # 1

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [7]:
ps = [PauliElement(0, 0, 1, 1), PauliElement(1, 0, 1, 1), PauliElement(1, 1, 1, 1), PauliElement(0, 1, 1, 1)]

In [ ]:
class Cifford:
    def __init__(self, p, q):
        self.p = p
        self.q = q
        self.elements = self._get_elements(p, q)
    def _get_elements(self, p, q):
        ps = []
        if p==0:
            ps.append(1)
        
